### ISSUE TITLE
解决住房问题的根本办法

### ISSUE THREAD

**Issue by 2775468731** [laoshenkaopu/kkndme_tianya#15]
有钱人买着一堆房，坐着收房租，看着抬房价，啥事不干锦衣玉食，钱也花不完；

打工人租着房打着工存着钱，丝毫不敢浪费一分钱，搞了一辈子就为了给子女还银行的房贷；

你说合理吗？

还有一堆人，后悔自己当时没有及时买房，当时买了房价必涨，哎，自己就赚到了，就很开心是吗？独善其身，自己过得好就行了，别人买不买得起房跟自己有啥关系，甚至自己更乐意看房价涨个不停，涨到就是赚到，是吗？

要知道，资源是有限的，一堆号称“精英”的10%的人占领了大部分资源，那90%的普通人就只能去尝试去争夺剩余的“汤汁”，他们怎么办？内卷呗，抬价呗。

人之初，性本恶。

你房子合理，坐落在比较核心的位置，贵些是合理的，但是你不应该让一个或几个人把贵的这块区域直接给“垄断”了再慢慢的卖出去赚钱，把这事放大一下看，全国有多少人手上有一堆房？

房子属性比较特殊，不应该以商品的方式进行销售，否则肯定有一大堆人去想尽办法在上面牟利，挣了一堆钱，坐着收房租，他肯定香啊，难的就是那些苦苦打工的劳动者。

只有把资源做到**按量分配**，才能做到“**以人为本**”，而不是“**以有钱人为本**”

**Comment by luis-allan** [comment]
真想问问你几岁了，怎么这么天真啊。。

**Comment by 2775468731** [comment]
> 真想问问你几岁了，怎么这么天真啊。。

有能耐给出你的高见呗，只会说风凉话，讲不出所以然，有什么能耐？显得自己很牛逼？那你在下面说明你的解决方案啊，只知道扯屁话有什么用？five

**Comment by DaphneChang** [comment]
> 有能耐给出你的高见呗，只会说风凉话，讲不出所以然，有什么能耐？显得自己很牛逼？那你在下面说明你的解决方案啊，只知道扯屁话有什么用？你是要把抽象思维贯彻到极致是吧

感觉你没有认真看这个帖子，里面解释了zf并不关心“那些苦苦打工的劳动者”，最在意的是农民，因为自古以来农民起义会推翻政权。农名在意的是什么？是温饱
操心房价的打工者，已经脱离了只关注吃饱的那个阶级。这个阶级的人买不起房会抱怨，但是绝不会对社会稳定产生什么质的影响。

**Comment by 2775468731** [comment]
> > 有能耐给出你的高见呗，只会说风凉话，讲不出所以然，有什么能耐？显得自己很牛逼？那你在下面说明你的解决方案啊，只知道扯屁话有什么用？你是要把抽象思维贯彻到极致是吧
> 
> 感觉你没有认真看这个帖子，里面解释了zf没那么在意“那些苦苦打工的劳动者”，更在意的是农民，因为自古以来农民起义会推翻政权。农民在意的是什么？是温饱 操心房价的打工者，已经脱离了只关注吃饱的那个阶层。这个阶层的人买不起房会抱怨，但是绝不会对社会稳定产生什么质的影响。

我并不否认你的看法，但我的论题并不是社会稳定因素，而是说依靠抬高房价成为人上人这种现象，存在的确是合理，但这种现象跟古时候的地主有什么分别？

**Comment by 2775468731** [comment]
工作需要缴纳税款，那房租是房东的收入，是不是也应该由房东缴纳税款？
